
version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    restart: always

volumes:
  node_modules: {}
